### ISSUE TITLE
Implement isSuffixOf for length indexed vector (Vec)?

### ISSUE THREAD

**Issue by ivanbrennan** [goldfirere/video-resources#3]
I've really been enjoying your videos, and currently working through the exercises/videos covering length indexed vectors. But I'm totally stuck on how to implement [`isSuffixOf`](https://github.com/goldfirere/video-resources/blob/684a57d25b1b4f5fa5d6bfca5f670b613766695c/2021-04-13-vectors/before/Vec.hs#L51), and as it isn't covered in any of the videos, I'm curious if you have any advice about how to get unblocked?

After banging my head against the wall for a while, I resorted to reading through the implementation for standard Haskell lists ([link](https://hackage.haskell.org/package/base-4.16.3.0/docs/src/Data.OldList.html#isSuffixOf)), but that just led me down a different dead end.

**Comment by user7230724** [comment]
@ivanbrennan

```hs
isSuffixOf :: (Eq a) => Vec n a -> Vec m a -> Bool
isSuffixOf xs ys = vecEq xs ys || case ys of
  Nil -> False
  _ :> ys' -> isSuffixOf xs ys'

vecEq :: (Eq a) => Vec n a -> Vec m a -> Bool
vecEq Nil Nil = True
vecEq (x :> xs) (y :> ys) = x == y && vecEq xs ys
vecEq _ _ = False
```

**Comment by goldfirere** [comment]
Thanks @user7230724! And, sorry to miss this when you posted @ivanbrennan! Closing as resolved.
